function [] = TempAlignNeuralData()
AlignNeuralData('/Users/dusiyi/Documents/Multifirefly-Project/all_monkey_data/neural_data/monkey_Bruno/data_0323/m51s005.plx', ...
    '/Users/dusiyi/Documents/Multifirefly-Project/all_monkey_data/time_calibration/monkey_Bruno/data_0323/neural_event_time.txt', ...
    1500)
end